### ISSUE TITLE
Preserve blanks when in text node

### ISSUE THREAD

**Issue by paed01** [atlassubbed/atlas-html-stream#1]
First of all: Thank you for an excellent and blazing fast library. It's pretty clever to pass a stream. It enables us to pipe it to another transformer.

## Description
We use your library (v1.0.1) for parsing and filtering markup before sending it to the client. Hence, the markup is reassembled after parsed. Environment: node v8.12.

Consider this original markup:
```html
Title: <b>Jan Bananberg</b>
```
Since trailing whitespaces are removed when parsing, the result after reassembly would be:
```html
Title:<b>Jan Bananberg</b>
```
which will be displayed as: Title:**Jan Bananberg** instead of Title: **Jan Bananberg**

## Suggestion
I fully understand the complexity of whitespaces in HTML, so IMHO, may I suggest an option to preserve blankspace, e.g. `HtmlParser({ preserveBlankspace: true })`. Leave it up to the developer so to speak.

**Comment by atlassubbed** [comment]
Hi @paed01. First of all, I'm glad you like the library! At first, this was meant for efficient scraping with https://github.com/atlassubbed/atlas-query-stream, and I purposefully ignored all whitespace. I think your suggestion is good, so I will review your PR. Thanks for submitting the issue 😄

**Comment by atlassubbed** [comment]
I just merged #2 and published the changes under `1.1.0` on npm. I'm gonna close this -- thanks for your contribution @paed01.
